# Generated by Django 5.0.4 on 2024-04-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Untitled post", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reply",
            name="content",
            field=models.TextField(default="Empty reply"),
            preserve_default=False,
        ),
    ]
